added template for lawn_mower, working with RCOverride
kas-lab/pipeline_inspection pull request #16
Opened 2022-09-27 12:26 UTC by jeroenzwan

Added lawn_mower template using RCOverride

2022-10-19 16:16 UTC, Rezenders commented on scripts/lawn_mower.py
> +        self.state_sub
Why is this line here? Not doing anything

2022-10-19 16:30 UTC, Rezenders requested changes
How should I test this? Running ardusub SITL + the pipeline_env launchfile + each script separately? 
Scripts don't have execute permission, make them executable `chmod +x ...`
Remove `.lawn_mower.py.swp`. Better to include a `.gitignore` file

2022-10-19 16:30 UTC, Rezenders commented on CMakeLists.txt
> +install(DIRECTORY launch
Missing to also install scripts

2022-10-19 16:30 UTC, Rezenders commented on scripts/lawn_mower.py
> +        self.state_sub
Why is this line here? Not doing anything

2022-10-19 16:30 UTC, Rezenders commented on CMakeLists.txt
> +install(DIRECTORY launch
Something like this:
```
install(PROGRAMS
  scripts/lawn_mower.py
  DESTINATION lib/${PROJECT_NAME}
)
```

2022-11-02 09:48 UTC, jeroenzwan commented on CMakeLists.txt
> +install(DIRECTORY launch
Added the requested changes

2022-11-07 09:56 UTC, merged